server:
  port: 8802
spring:
  application:
    name: could-stream-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings: #服务的整合处理
        myChannel-in-0: #这个名字是一个通道的名称, 新版本格式 函数名-{out/in}-{index}
          destination: studyExchange #表示要使用Exchange的名称定义
          content-type: application/json #设置消息类型，本次为json, 文本则设置”text/plain"
          #binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5
    instance-id: consumer-8802.com #在信息列表时显示主机名称
    prefer-ip-address: true #访问的路径变为IP地址